### ISSUE TITLE
suggestion: issue/pr template

### ISSUE THREAD

**Issue by sadiejay** [GV14982/tech-friends-battle-snake#2]
Problem:
   -  (This is one of my fav issues to suggest 😊) Currently, there are no guidelines for what information issues and pull requests should contain. This adds ambiguity for contributors on what to include when submitting issues / prs and adds more time and mental burden for maintainers when understanding why or how a contribution could be considers.

Proposed solution:
 -  I suggest creating an action by adding yml files to the .github directory that automatically formats incoming issues and prs with desired information that maintainers would like to know and to guide contributors to adding helpful information about their issue/pr.
  -  The action could be as robust as creating a landing page to different types of issue templates, automatically labeling issues and closing prs or as simple as sections with headings informing contributors what information to include.

Additional Resources:
  -  Examples:
     - Virtual Coffee repo — https://github.com/Virtual-Coffee/virtualcoffee.io/issues/new/choose
     - Open Sauced docs repo — https://github.com/open-sauced/docs.opensauced.pizza/issues/new/choose
     - A Call for Code repo — https://github.com/Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System/blob/main/.github/pull_request_template.md
     - Carbon Code by IBM repo — https://github.com/IBM/carbon-ui-builder/issues/new/choose

**Comment by GV14982** [comment]
So as far as formatting, I feel like we can check formatting in CI and just fail the build if it has issues.
